### ISSUE TITLE
インストールエラー

### ISSUE THREAD

**Issue by gabriel-tessier** [hhatto/pgmagick#10]
こんにちは,
pgmagickインストールしましたけどこのエラー出ました：

した事
`sudo yum install boost-devel`
`sudo yum install GraphicsMagick-c++-devel`
`sudo yum install gcc-c++`
`sudo pip install pgmagick`
> You are using pip version 6.1.1, however version 8.1.2 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> Collecting pgmagick
>   Using cached pgmagick-0.6.2.tar.gz
> Installing collected packages: pgmagick
>   Running setup.py install for pgmagick
>     Complete output from command /usr/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-VK29z6/pgmagick/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Ob_TKo-record/install-record.txt --single-version-externally-managed --compile:
>     include header path: /usr/include/GraphicsMagick/
>     boost lib: boost_python-mt
>     library path: /usr/lib64/libGraphicsMagick++
>     GraphicsMagick version: 1.3.24
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib.linux-x86_64-2.7
>     creating build/lib.linux-x86_64-2.7/pgmagick
>     copying pgmagick/_version.py -> build/lib.linux-x86_64-2.7/pgmagick
>     copying pgmagick/api.py -> build/lib.linux-x86_64-2.7/pgmagick
>     copying pgmagick/__init__.py -> build/lib.linux-x86_64-2.7/pgmagick
>     running build_ext
>     building 'pgmagick._pgmagick' extension
>     creating build/temp.linux-x86_64-2.7
>     creating build/temp.linux-x86_64-2.7/src
>     gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -I/usr/include/GraphicsMagick/ -I/usr/include/python2.7 -c ./src/_SparseColorMethod.cpp -o build/temp.linux-x86_64-2.7/./src/_SparseColorMethod.o -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_24 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_22 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_20 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_6 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_x -D_LIBRARY_VERSION="1.3.24"
>     gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -I/usr/include/GraphicsMagick/ -I/usr/include/python2.7 -c ./src/_DrawableSkewY.cpp -o build/temp.linux-x86_64-2.7/./src/_DrawableSkewY.o -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_24 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_22 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_20 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_6 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_x -D_LIBRARY_VERSION="1.3.24"
> 
.....
> gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -I/usr/include/GraphicsMagick/ -I/usr/include/python2.7 -c ./src/_DrawableTranslation.cpp -o build/temp.linux-x86_64-2.7/./src/_DrawableTranslation.o -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_24 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_22 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_20 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_6 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_x -D_LIBRARY_VERSION="1.3.24"
>     gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -I/usr/include/GraphicsMagick/ -I/usr/include/python2.7 -c ./src/_DrawablePolygon.cpp -o build/temp.linux-x86_64-2.7/./src/_DrawablePolygon.o -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_24 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_22 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_20 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_6 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_x -D_LIBRARY_VERSION="1.3.24"
>     gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -I/usr/include/GraphicsMagick/ -I/usr/include/python2.7 -c ./src/_PathCurvetoArgs.cpp -o build/temp.linux-x86_64-2.7/./src/_PathCurvetoArgs.o -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_24 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_22 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_20 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_6 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_x -D_LIBRARY_VERSION="1.3.24"
>     gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -I/usr/include/GraphicsMagick/ -I/usr/include/python2.7 -c ./src/_StyleType.cpp -o build/temp.linux-x86_64-2.7/./src/_StyleType.o -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_24 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_22 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_20 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_6 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_x -D_LIBRARY_VERSION="1.3.24"
>     gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -I/usr/include/GraphicsMagick/ -I/usr/include/python2.7 -c ./src/_Image.cpp -o build/temp.linux-x86_64-2.7/./src/_Image.o -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_24 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_22 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_20 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_6 -DPGMAGICK_LIB_GRAPHICSMAGICK_1_3_x -D_LIBRARY_VERSION="1.3.24"
>     gcc: internal compiler error: 強制終了 (program cc1plus)
>     Please submit a full bug report,
>     with preprocessed source if appropriate.
>     See <http://bugzilla.redhat.com/bugzilla> for instructions.
>     error: command 'gcc' failed with exit status 4
>     
>     ----------------------------------------
>     Command "/usr/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-VK29z6/pgmagick/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Ob_TKo-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-VK29z6/pgmagick
> 

Hattoriさんのブログから読んだ：
> Problem
> 
>     英語勉強せず
> 
> Try
> 
>     英語勉強

私も日本語勉強したけど。。。
手伝ってください！m(__)m

**Comment by hhatto** [comment]
こんにちは
Thanks for reporting.

Could you tell me a little more about the environment?
* Linux Distribution and version
* using Vagrant?

Are you using a Vagrant(VirtualBox)? What the same situation as this?
https://bitbucket.org/hhatto/pgmagick/issues/38/cant-install-pgmagick-on-server

**Comment by gabriel-tessier** [comment]
Thanks for the reply,
I installed it on Amazon on a t2.micro instance with 1GB memory, I'll give a try on a bigger instance with more memory and close the issue if it's solve.

**Comment by gabriel-tessier** [comment]
It take a while but now it install correctly, so it need 2 GB of memory to be installed.

Thanks again, I can close this issue.

sudo pip install pgmagick
You are using pip version 6.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pgmagick
  Downloading pgmagick-0.6.2.tar.gz (40kB)
    100% |████████████████████████████████| 40kB 5.5MB/s 
Installing collected packages: pgmagick
  Running setup.py install for pgmagick
Successfully installed pgmagick-0.6.2
