### ISSUE TITLE
ImportError: undefined symbol: IsEventLogging

### ISSUE THREAD

**Issue by asgoel** [hhatto/pgmagick#11]
I manually built pgmagick using custom built GraphicsMagick++ (version 1.3.25) and custom built boost (version 1.58.0). I receive the following error when I try to import something simple.

```
>>> from pgmagick.api import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pgmagick/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pgmagick/_pgmagick.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/pgmagick/_pgmagick.py", line 6, in __bootstrap__
ImportError: /home/ec2-user/.python-eggs/pgmagick-0.6.2-py2.7-linux-x86_64.egg-tmp/pgmagick/_pgmagick.so: undefined symbol: IsEventLogging
```

Any ideas?

**Comment by hhatto** [comment]
Could you check the following points?
* result of `$ ./configure` ( `config.log` file )
* link libGraphicsMagick? `$ ldd /path/to/libGraphicsMagick++.so`

**Comment by asgoel** [comment]
ah, i forgot to build GraphicsMagick with the shared headers, that solved the problem.
Now I have a problem where I can't import pgmagick unless I am in the pgmagick folder. Otherwise I get the following error:

```
>>> import pgmagick
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pgmagick/__init__.py", line 1, in <module>
    from pgmagick import _pgmagick
ImportError: cannot import name _pgmagick
```

I installed it using `python setup.py install` instead of using `pip`. Is there a way to install such that I can access it anywhere as long as I am in my virtualenv?

**Comment by hhatto** [comment]
https://github.com/hhatto/pgmagick/issues/7#issuecomment-213394713
same problem? Current working directory is not pgmagick directory?

**Comment by asgoel** [comment]
Yes I saw that, but I was wondering if there was a way to get around that. I.e. have it work **without** pgmagick being the current directory.

**Comment by hhatto** [comment]
As it is considered, _pgmagick.so file is not exist.

Could you attach a `python setup.py install` 's complete log or URL? (or `pip install` 's log)
For example : https://gist.github.com/hhatto/b765a6d2b1be1ec82de405e0891f0ad7

**Comment by asgoel** [comment]
https://gist.github.com/asgoel/d6483a1b8ef317b2cf31f0a1d9dd627e

**Comment by hhatto** [comment]
* include `pgmagick/_pgmagick.so` in `/home/ec2-user/venv/lib64/python2.7/site-packages/pgmagick-0.6.2_vessel-py2.7-linux-x86_64.egg` ?

```
$ unzip -l /home/ec2-user/venv/lib64/python2.7/site-packages/pgmagick-0.6.2_vessel-py2.7-linux-x86_64.egg
  Length     Date   Time    Name
 --------    ----   ----    ----
        1  09-24-16 23:27   EGG-INFO/dependency_links.txt
       22  09-24-16 23:27   EGG-INFO/native_libs.txt
     6493  09-24-16 23:27   EGG-INFO/PKG-INFO
     3424  09-24-16 23:27   EGG-INFO/SOURCES.txt
        9  09-24-16 23:27   EGG-INFO/top_level.txt
        1  09-24-16 23:27   EGG-INFO/zip-safe
     7540  06-01-16 01:19   pgmagick/__init__.py
    20134  09-24-16 23:27   pgmagick/__init__.pyc
      285  09-24-16 23:27   pgmagick/_pgmagick.py
      565  09-24-16 23:27   pgmagick/_pgmagick.pyc
  5906932  09-24-16 23:27   pgmagick/_pgmagick.so
       29  09-24-16 23:21   pgmagick/_version.py
      182  09-24-16 23:27   pgmagick/_version.pyc
    29105  06-01-16 01:19   pgmagick/api.py
    35355  09-24-16 23:27   pgmagick/api.pyc
 --------                   -------
  6010077                   15 files
```

* include `/home/ec2-user/venv/lib64/python2.7/site-packages` in `sys.path` ?

**Comment by asgoel** [comment]
that worked. thanks!
