### ISSUE TITLE
PixelPacket and Image.get_pixels() support

### ISSUE THREAD

**Issue by komackaj** [hhatto/pgmagick#13]
Quoted from https://bitbucket.org/hhatto/pgmagick/issues/26/ 

> Will there someday be support for direct pixel access via functions like Image.get_pixels(...)? Is there some limitation preventing its implementation, or is it just a matter of work and time?

I'm quite interested in this feature and might be able to implement it - are you open to PRs?

**Comment by hhatto** [comment]
@komackaj Sorry for late reply.

> I've made some progress that can be seen here and it seems to be working, but the implementation seems clumsy to me.

Great work!!

This implementation already fulfills the function.
I would be happy if you could issue a pull request.

**Comment by komackaj** [comment]
Hi,
I've managed to make another implementation using IMHO a little bit better approach - proxy objects - WIP [here](https://github.com/hhatto/pgmagick/compare/master...komackaj:image_pixels_access2).

First, it doesn't create Python object for every pixel, until not accessed. Next, it allows adding custom methods to returned ArrayProxy (e.g. for exposing raw data). And finally, we can better manage lifespan of original Image in PixelPacketArrayProxy.

I'll simplify the code using boost::bind and try to improve lifetime management. Hopefully, it will go without problems and I'll send PR soon.

**Comment by komackaj** [comment]
I was able to make ArrayProxy work after buffer's parent is no longer valid by optionally holding some kind of reference to it (shallow copy of `Magick::Image` in case of PixelPacketArrayProxy).

Simplifying the code without using C++11 syntax is quite hard, so I've stuck with the helper functions.
