### ISSUE TITLE
Cannot create Blob from bytes in python3

### ISSUE THREAD

**Issue by komackaj** [hhatto/pgmagick#15]
This code works with python2 (when data is 'str') but not with python3 (when data is 'bytes')
``` python
# test.py
from __future__ import print_function
from pgmagick import Blob, Image

# load any image data from file
with open('test.png', 'rb') as f:
    data = f.read()

print ("Image data type is", type(data))
b = Blob(data)
img = Image(b)
print ("File width is", img.size().width())
```

With `# python2 test.py` gives
```
Image data type is <type 'str'>
File width is 16 # or whatever
```

with `python3 test.py` gives
```
Image data type is <class 'bytes'>
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    b = Blob(data)
  File "/usr/lib/python3/dist-packages/pgmagick/__init__.py", line 16, in __init__
    _pgmagick.Blob.__init__(self, *args)
Boost.Python.ArgumentError: Python argument types in
    Blob.__init__(Blob, bytes)
did not match C++ signature:
    __init__(_object*, Magick::Blob)
    __init__(Magick::Blob {lvalue}, std::string)
    __init__(_object*)
```

It is possible to bypass it using
```
b = Blob()
b.update(data)
```
but it seems, that initializing Blob using [update_wrapper ](https://github.com/hhatto/pgmagick/blob/ff93abcc74da879255b7dcd2a895c955916f722f/src/_Blob.cpp#L32) doesn't work in python3

Tested on Debian Jessie using backported packaging from Stretch and libboost-python-dev=1.55.0.2. May anyone confirm?

**Comment by hhatto** [comment]
Thank you for reporting.

fixed in 8677b5577e429e3e6f6054fe8c6552d559b01ca5

Could you try once again in latest master?

**Comment by komackaj** [comment]
Hi,
I can confirm that the bug is solved in current master.
Thanks for the patch

**Comment by hhatto** [comment]
pgmagick version 0.6.3 has been released.

https://pypi.python.org/pypi/pgmagick/0.6.3
