### ISSUE TITLE
Cannot access blob data in python3

### ISSUE THREAD

**Issue by komackaj** [hhatto/pgmagick#19]
Maybe related to #15 
This code works with python2 (when data is 'str') but not with python3 (when data is 'bytes')
``` python
from __future__ import print_function
from pgmagick import Blob, Image

# load any image data from file
image = Image('logo.jpg')
blob = Blob()
image.write(blob)
print ("Image length is", blob.length())
print ("Data type is", type(blob.data))
```

With `# python2 test.py` gives
```
Image length is 10958
Data type is <type 'str'>
```

with `python3 test.py` gives
```
Image length is 10958
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    print ("Data type is", type(blob.data))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

Any access on blob.data results with UnicodeDecodeError, I assume, there is implicit conversion to string, that fails with binary data.

Tested on Debian Stretch with python3-pgmagick=0.6.4-1

**Comment by hhatto** [comment]
What the same situation as #17 ?

This changeset is not released to PyPI.
Could you try once again in latest master?

If it seems to be no problem releasing 0.6.5 to PyPI.

Thanks

**Comment by komackaj** [comment]
Sorry, I didn't notice that MR, with current master everything works perfectly.
Many thanks.

**Comment by hhatto** [comment]
version 0.6.5 has been released.

https://pypi.python.org/pypi/pgmagick/0.6.5
