### ISSUE TITLE
add Image.resize() and related FilterTypes

### ISSUE THREAD

**Issue by stefantalpalaru** [hhatto/pgmagick#21]
Both _scale()_ and _sample()_ give low quality results and the only filter-based resizing method is _zoom()_ which is limited to the default filter and has a non-intuitive name.

http://www.graphicsmagick.org/Magick++/Image.html#resize

http://www.graphicsmagick.org/Magick++/Image.html#filtertype

**Comment by hhatto** [comment]
@stefantalpalaru 

Sorry for late reply.
How about this? 148891fb9f2edee3c739a68495a2eb1c48a96f98

**Comment by stefantalpalaru** [comment]
Perfect!

I see in README.rst, in the scale example, that you set a custom filter type for the image but I don't think scale() takes it in consideration. From what I understand, only zoom() and resize() do. Can you check that?

**Comment by hhatto** [comment]
> I see in README.rst, in the scale example, that you set a custom filter type for the image but I don't think scale() takes it in consideration. From what I understand, only zoom() and resize() do. Can you check that?

That's right 😄 
fix in 057d024641abe02faff7221f581cbb69650fd3e8
