### ISSUE TITLE
pgmagick on Ubuntu 16.04

### ISSUE THREAD

**Issue by MeghaMaheshwari** [hhatto/pgmagick#28]
Hi I am trying to install pgmagick on Ubuntu 16.04 but it gives me the error 

"ImportError: No module named 'pgmagick'

I did the following steps:

sudo apt-get update
sudo apt-get install graphicsmagick
sudo apt-get install libmagick++-dev
sudo apt-get install libgraphicsmagick++1-dev
sudo apt-get install libboost-python-dev
sudo pip install pgmagick

**Comment by hhatto** [comment]
Thanks for reporting.

Is not this the same case?

https://github.com/hhatto/pgmagick/issues/7#issuecomment-213418259

**Comment by komackaj** [comment]
@MeghaMaheshwari 
Hi, I was unable to reproduce inside of clean Docker image.
Could you run `ls -la . >import.log && python -vvc 'import pgmagick' >>import.log 2>&1`
and provide us with content of import.log ?

**Comment by komackaj** [comment]
@MeghaMaheshwari  
Have you resolved your issue? If not can you provide us with an output of the aforementioned command?

**Comment by hhatto** [comment]
Please reopen if necessary.
