### ISSUE TITLE
'Image' object has no attribute 'resize'

### ISSUE THREAD

**Issue by syncml** [hhatto/pgmagick#36]
```
>>> import pgmagick
>>> from pgmagick import Image, FilterTypes,gminfo
>>> 
>>> print gminfo.library
GraphicsMagick
>>> print gminfo.version
1.3.x
>>> 
>>> im = Image('koala.jpg')
>>> im.filterType(FilterTypes.SincFilter)
>>> im.resize('100x100')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Image' object has no attribute 'resize'
>>> im.write('output.jpg')
```

**Comment by komackaj** [comment]
Hi,
thank you for the report. It seems like you use an older version of GraphicsMagick (`.resize()` method is available in GraphicsMagick from 1.3.21 onwards, maybe you could use `.zoom()` that internally uses resize for older versions) or there is an error in library version detection process. 

Could you provide us with a little more information specifically:
- how did you install pgmagick (using pip / compiled from source)
- what is your version of GraphicsMagick
- what OS distribution / version you use

**Comment by syncml** [comment]
@komackaj 

 Thanks for ur reply.

- how did you install pgmagick (using pip / compiled from - source)
   pip install pgmagick

- what is your version of GraphicsMagick
   GraphicsMagick 1.3.25 2016-09-05 Q8

- what OS distribution / version you use
   Ubuntu 14.04.4 LTS

**Comment by syncml** [comment]
Other question,thank you very much:)

Can you give me an example? How should gm convert command be written if it is written in pgmagick?

eg:
`convert +profile '*' abc.jpg -quality 80 -resize '280x140^>' -gravity Center -crop 280x140+0+0 +repage abc_280x140.jpg`

**Comment by komackaj** [comment]
Do you use a local build of graphicsmagick or nonstandard package repository? According to [this](https://packages.ubuntu.com/trusty/libgraphicsmagick++1-dev) only 1.3.18 is available in your OS.

**Comment by syncml** [comment]
@komackaj 
Yes, I use a local build of graphicsmagick.
By the way,Please tell me how to use '-gravity Center' when I crop a image. 
I have read magick++ API,but  did not find the relevant information.
i'm so mad

**Comment by komackaj** [comment]
Do you have any other version of libgraphicsmagick++-dev installed? If so, pip probably used that one. Could you try to reinstall using `pip install --upgrade --force-reinstall pgmagick` and post content of your `pip.log`?

As for gravity - `gm` seems to set [this attribute](http://hg.code.sf.net/p/graphicsmagick/code/file/1b47e0078e05/magick/image.h#l749) in C API but it cannot be passed in `.crop` using C++ API as for example in `annotate`, try to ask in GM mailing list.

One could try to use `.extent` method with gravity and then crop as a hack, but it looks like pgmagick currently provides  it [](https://github.com/hhatto/pgmagick/blob/master/src/_Image.cpp#L160)

**Comment by komackaj** [comment]
Sorry for premature closing

**Comment by syncml** [comment]
@komackaj 
pgmagick version is ：
```
pip list |grep pgmagick
pgmagick (0.5.7)
```
So I run commond: `pip install --upgrade --force-reinstall pgmagick`

print error :

```
/usr/bin/ld: cannot find -lboost_python

collect2: error: ld returned 1 exit status

error: command 'c++' failed with exit status 1

----------------------------------------
  Can't roll back pgmagick; was not uninstalled
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/pgmagick/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-sRAByD-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/pgmagick
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)
```

then : `apt-get install libboost-python1.40-dev`

print :

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libboost-python1.40-dev
E: Couldn't find any package by regex 'libboost-python1.40-dev'
```

**Comment by komackaj** [comment]
@syncml 
Hi, this makes sense... Trying to mix OS-packages and pip packages isn't a great idea.
First challenge is to force python to use correct one, I assume OS owned will be used by default. So first try to uninstall system pgmagick if you want to use the one from pip.

In your pip log you can see that pip uses system libgraphicsmagick
`Found version 1.3.18 in file /usr/lib/pkgconfig/GraphicsMagick++.pc`
that doesn't have `.resize` method. 

Could you try to move your local libgraphicsmagick header files to
`/usr/local/include/GraphicsMagick/` and libraries to `/usr/local/lib/` (`make install` in GM build folder should do it), reinstall pgmagick using pip (so it uses your local GM build) and check that setup.py will prefer it?

**Comment by syncml** [comment]
Thank you. I'll try it later
