### ISSUE TITLE
Image.extent not available for GM

### ISSUE THREAD

**Issue by komackaj** [hhatto/pgmagick#37]
Image doesn't have `extent` method [available in GM](http://www.graphicsmagick.org/Magick++/Image.html#extent) due to [this](https://github.com/hhatto/pgmagick/blob/master/src/_Image.cpp#L160)

We should examine since which version is it available in GM C++ API and make it accessible from pgmagick.

**Comment by hhatto** [comment]
Good catch 👍 

Thanks

**Comment by bsechter-unext** [comment]
I really want to used this function.

**Comment by komackaj** [comment]
@hhatto 
Should we release?

**Comment by hhatto** [comment]
@bsechter-unext @komackaj 
pgmagick 0.7.3 has been released.
https://pypi.python.org/pypi/pgmagick/0.7.3

Thanks
