### ISSUE TITLE
Build error with Boost 1.60

### ISSUE THREAD

**Issue by tomka** [hhatto/pgmagick#4]
When I try to build with Boost 1.60 (released December 17) I get the following error:

```
    In file included from /usr/include/boost/python/object/make_instance.hpp:10:0,
                     from /usr/include/boost/python/object/make_ptr_instance.hpp:8,
                     from /usr/include/boost/python/to_python_indirect.hpp:11,
                     from /usr/include/boost/python/converter/arg_to_python.hpp:10,
                     from /usr/include/boost/python/call.hpp:15,
                     from /usr/include/boost/python/object_core.hpp:14,
                     from /usr/include/boost/python/args.hpp:25,
                     from /usr/include/boost/python.hpp:11,
                     from ./src/_Blob.cpp:1:
    /usr/include/boost/python/converter/registered.hpp: In instantiation of ‘const boost::python::converter::registration& boost::python::converter::detail::registry_lookup1(boost::type<Target>) [with T = void]’:
    /usr/include/boost/python/converter/registered.hpp:104:80:   required from ‘const boost::python::converter::registration& boost::python::converter::detail::registered_base<void>::converters’
    /usr/include/boost/python/converter/arg_from_python.hpp:269:61:   required from ‘boost::python::converter::pointer_arg_from_python<T>::pointer_arg_from_python(PyObject*) [with T = void*; PyObject = _object]’
    /usr/include/boost/python/arg_from_python.hpp:70:18:   required from ‘boost::python::arg_from_python<T>::arg_from_python(PyObject*) [with T = void*; PyObject = _object]’
    /usr/include/boost/preprocessor/iteration/detail/local.hpp:37:9:   required from ‘PyObject* boost::python::detail::caller_arity<3u>::impl<F, Policies, Sig>::operator()(PyObject*, PyObject*) [with F = void (*)(Magick::Blob&, void*, long unsigned int); Policies = boost::python::default_call_policies; Sig = boost::mpl::vector4<void, Magick::Blob&, void*, long unsigned int>; PyObject = _object]’
    /usr/include/boost/python/object/py_function.hpp:38:33:   required from ‘PyObject* boost::python::objects::caller_py_function_impl<Caller>::operator()(PyObject*, PyObject*) [with Caller = boost::python::detail::caller<void (*)(Magick::Blob&, void*, long unsigned int), boost::python::default_call_policies, boost::mpl::vector4<void, Magick::Blob&, void*, long unsigned int> >; PyObject = _object]’
    ./src/_Blob.cpp:44:1:   required from here
    /usr/include/boost/python/converter/registered.hpp:93:30: error: no matching function for call to ‘registry_lookup2(void (*)())’
           return registry_lookup2((T(*)())0);
                                  ^
    /usr/include/boost/python/converter/registered.hpp:83:3: note: candidate: template<class T> const boost::python::converter::registration& boost::python::converter::detail::registry_lookup2(T& (*)())
       registry_lookup2(T&(*)())
       ^
    /usr/include/boost/python/converter/registered.hpp:83:3: note:   template argument deduction/substitution failed:
    /usr/include/boost/python/converter/registered.hpp:93:30: note:   mismatched types ‘T&’ and ‘void’
           return registry_lookup2((T(*)())0);
                                  ^
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/tom/.virtualenvs/catmaid-new/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-HAhCpc/pgmagick/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-amWu4y-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/tom/.virtualenvs/catmaid-new/include/site/python2.7/pgmagick" failed with error code 1 in /tmp/pip-build-HAhCpc/pgmagick
```

**Comment by kiefermat** [comment]
I have the same problem on Mac OS X:
`In file included from ./src/_Blob.cpp:1:
    In file included from /usr/local/include/boost/python.hpp:11:
    In file included from /usr/local/include/boost/python/args.hpp:25:
    In file included from /usr/local/include/boost/python/object_core.hpp:14:
    In file included from /usr/local/include/boost/python/call.hpp:15:
    In file included from /usr/local/include/boost/python/converter/arg_to_python.hpp:10:
    In file included from /usr/local/include/boost/python/to_python_indirect.hpp:11:
    In file included from /usr/local/include/boost/python/object/make_ptr_instance.hpp:8:
    In file included from /usr/local/include/boost/python/object/make_instance.hpp:10:
    /usr/local/include/boost/python/converter/registered.hpp:93:14: error: no matching function for call to 'registry_lookup2'
          return registry_lookup2((T(*)())0);
                 ^~~~~~~~~~~~~~~~
    /usr/local/include/boost/python/converter/registered.hpp:104:64: note: in instantiation of function template specialization 'boost::python::converter::detail::registry_lookup1<void>' requested here
      registration const& registered_base<T>::converters = detail::registry_lookup1(type<T>());
                                                                   ^
    /usr/local/include/boost/python/converter/arg_from_python.hpp:269:88: note: in instantiation of static data member 'boost::python::converter::detail::registered_base<void>::converters' requested here
            p == Py_None ? p : converter::get_lvalue_from_python(p, registered_pointee<T>::converters))
                                                                                           ^
    /usr/local/include/boost/python/arg_from_python.hpp:70:7: note: in instantiation of member function 'boost::python::converter::pointer_arg_from_python<const void *>::pointer_arg_from_python' requested here
        : base(source)
          ^
    /usr/local/include/boost/preprocessor/iteration/detail/local.hpp:37:9: note: in instantiation of member function 'boost::python::arg_from_python<const void *>::arg_from_python' requested here
            BOOST_PP_LOCAL_MACRO(1)
            ^
    /usr/local/include/boost/python/detail/caller.hpp:209:35: note: expanded from macro 'BOOST_PP_LOCAL_MACRO'
    #  define BOOST_PP_LOCAL_MACRO(i) BOOST_PYTHON_ARG_CONVERTER(i)
                                      ^
    /usr/local/include/boost/python/detail/caller.hpp:128:13: note: expanded from macro 'BOOST_PYTHON_ARG_CONVERTER'
         c_t##n c##n(get(mpl::int_<n>(), inner_args));                              \
                ^
    <scratch space>:173:1: note: expanded from here
    c1
    ^
    /usr/local/include/boost/python/object/py_function.hpp:38:16: note: in instantiation of member function 'boost::python::detail::caller_arity<3>::impl<void (*)(_object *, const void *, unsigned long), boost::python::default_call_policies, boost::mpl::vector4<void, _object *, const void *, unsigned long> >::operator()' requested here
            return m_caller(args, kw);
                   ^
    /usr/local/include/boost/python/object/py_function.hpp:32:5: note: (skipping 7 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
        caller_py_function_impl(Caller const& caller)
        ^
    /usr/local/include/boost/python/init.hpp:149:62: note: in instantiation of function template specialization 'boost::python::detail::define_class_init_helper<0>::apply<boost::python::class_<Magick::Blob, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>, boost::python::default_call_policies, boost::mpl::vector2<const void *, unsigned long>, boost::mpl::size<boost::mpl::vector2<const void *, unsigned long> > >' requested here
            detail::define_class_init_helper<n_defaults::value>::apply(
                                                                 ^
    /usr/local/include/boost/python/def_visitor.hpp:31:29: note: in instantiation of function template specialization 'boost::python::init_base<boost::python::init<const void *, unsigned long, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_> >::visit<boost::python::class_<Magick::Blob, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> >' requested here
            v.derived_visitor().visit(c);
                                ^
    /usr/local/include/boost/python/def_visitor.hpp:67:29: note: in instantiation of function template specialization 'boost::python::def_visitor_access::visit<boost::python::def_visitor<boost::python::init<const void *, unsigned long, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_> >, boost::python::class_<Magick::Blob, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> >' requested here
            def_visitor_access::visit(*this, c);
                                ^
    /usr/local/include/boost/python/class.hpp:225:17: note: in instantiation of function template specialization 'boost::python::def_visitor<boost::python::init<const void *, unsigned long, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_> >::visit<boost::python::class_<Magick::Blob, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> >' requested here
            visitor.visit(*this);
                    ^
    ./src/_Blob.cpp:27:10: note: in instantiation of function template specialization 'boost::python::class_<Magick::Blob, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>::def<boost::python::init<const void *, unsigned long, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_> >' requested here
            .def(init< const void*, size_t >())
             ^
    /usr/local/include/boost/python/converter/registered.hpp:83:3: note: candidate template ignored: could not match 'type-parameter-0-0 &' against 'void'
      registry_lookup2(T&(*)())
      ^
    1 error generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------`

**Comment by hhatto** [comment]
fix in version 0.6.1.
Could you try install again with pgmagick version0.6.1? (or via homebrew-pgmagick)

**Comment by kiefermat** [comment]
I tried both on Mac with boost 1.60 and on Debian/Wheezy with boost 1.49. On both systems the package compiles and installes without errors and everything seems to work correctly.

Thanks a lot!

**Comment by hhatto** [comment]
:+1:
