### ISSUE TITLE
Import Error from pgmagick import _pgmagick

### ISSUE THREAD

**Issue by arycloud** [hhatto/pgmagick#49]
I have installed Pgmagic using `pip install pgmagick`  but when try to use it, it returns an Import error like this:
`<module>
    from pgmagick import _pgmagick
ImportError: dlopen(/Users/abdul/ImgSegEnv/lib/python3.6/site-packages/pgmagick/_pgmagick.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/opt/boost-python3/lib/libboost_python36.dylib
  Referenced from: /Users/abdul/ImgSegEnv/lib/python3.6/site-packages/pgmagick/_pgmagick.cpython-36m-darwin.so
  Reason: image not found`

**Comment by hhatto** [comment]
https://github.com/hhatto/pgmagick/issues/45#issuecomment-418240470

[memo] Mojave(macOS 10.14), Python3.6

**Comment by hhatto** [comment]
@arycloud 

Hi,

successfull install and test in my environment.

my environment:
* macOSX 10.14
* Python 3.7 (via homebrew)
* boost-python 1.67.0 (via homebrew)
* graphicsmagick 1.3.30 (via homebrew)
* pgmagick 0.7.4

Can you try the `pip` installation again by applying a `--force-reinstall` and `--no-cache-dir` option?
```
$ pip install --force-reinstall pgmagick
```

If the same error occurs, will you get the installation log? (url or files, etc...)

**Comment by hhatto** [comment]
No reply for a long time, so I will close it once.
If you are still experiencing the same problem, please open it again.
